/**
 * Standardized error codes for the API.
 * Format: DOMAIN.SPECIFIC_ERROR
 *
 * These codes enable programmatic error handling on the frontend
 * and provide consistent error identification across the API.
 */
export enum ErrorCode {
  // ============================================
  // Authentication Errors (AUTH.*)
  // ============================================
  AUTH_INVALID_CREDENTIALS = 'AUTH.INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED = 'AUTH.TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID = 'AUTH.TOKEN_INVALID',
  AUTH_EMAIL_NOT_VERIFIED = 'AUTH.EMAIL_NOT_VERIFIED',
  AUTH_ACCOUNT_LOCKED = 'AUTH.ACCOUNT_LOCKED',
  AUTH_TOO_MANY_ATTEMPTS = 'AUTH.TOO_MANY_ATTEMPTS',
  AUTH_EMAIL_ALREADY_EXISTS = 'AUTH.EMAIL_ALREADY_EXISTS',
  AUTH_INVALID_OTP = 'AUTH.INVALID_OTP',
  AUTH_OTP_EXPIRED = 'AUTH.OTP_EXPIRED',
  AUTH_PASSWORD_MISMATCH = 'AUTH.PASSWORD_MISMATCH',
  AUTH_WEAK_PASSWORD = 'AUTH.WEAK_PASSWORD',

  // ============================================
  // Authorization Errors (FORBIDDEN.*)
  // ============================================
  FORBIDDEN_INSUFFICIENT_PERMISSIONS = 'FORBIDDEN.INSUFFICIENT_PERMISSIONS',
  FORBIDDEN_RESOURCE_ACCESS = 'FORBIDDEN.RESOURCE_ACCESS',
  FORBIDDEN_ADMIN_REQUIRED = 'FORBIDDEN.ADMIN_REQUIRED',

  // ============================================
  // Validation Errors (VALIDATION.*)
  // ============================================
  VALIDATION_INVALID_INPUT = 'VALIDATION.INVALID_INPUT',
  VALIDATION_MISSING_FIELD = 'VALIDATION.MISSING_FIELD',
  VALIDATION_INVALID_FORMAT = 'VALIDATION.INVALID_FORMAT',
  VALIDATION_OUT_OF_RANGE = 'VALIDATION.OUT_OF_RANGE',
  VALIDATION_INVALID_ENUM = 'VALIDATION.INVALID_ENUM',

  // ============================================
  // Resource Not Found Errors (NOT_FOUND.*)
  // ============================================
  NOT_FOUND_USER = 'NOT_FOUND.USER',
  NOT_FOUND_ORDER = 'NOT_FOUND.ORDER',
  NOT_FOUND_COIN = 'NOT_FOUND.COIN',
  NOT_FOUND_EXCHANGE = 'NOT_FOUND.EXCHANGE',
  NOT_FOUND_EXCHANGE_KEY = 'NOT_FOUND.EXCHANGE_KEY',
  NOT_FOUND_PORTFOLIO = 'NOT_FOUND.PORTFOLIO',
  NOT_FOUND_ALGORITHM = 'NOT_FOUND.ALGORITHM',
  NOT_FOUND_STRATEGY = 'NOT_FOUND.STRATEGY',
  NOT_FOUND_BACKTEST = 'NOT_FOUND.BACKTEST',
  NOT_FOUND_CATEGORY = 'NOT_FOUND.CATEGORY',
  NOT_FOUND_RESOURCE = 'NOT_FOUND.RESOURCE',

  // ============================================
  // Conflict Errors (CONFLICT.*)
  // ============================================
  CONFLICT_DUPLICATE_RESOURCE = 'CONFLICT.DUPLICATE_RESOURCE',
  CONFLICT_EXCHANGE_KEY_EXISTS = 'CONFLICT.EXCHANGE_KEY_EXISTS',
  CONFLICT_EMAIL_EXISTS = 'CONFLICT.EMAIL_EXISTS',
  CONFLICT_STRATEGY_EXISTS = 'CONFLICT.STRATEGY_EXISTS',

  // ============================================
  // Business Rule Errors (BUSINESS.*)
  // ============================================
  BUSINESS_INSUFFICIENT_BALANCE = 'BUSINESS.INSUFFICIENT_BALANCE',
  BUSINESS_ORDER_CANNOT_CANCEL = 'BUSINESS.ORDER_CANNOT_CANCEL',
  BUSINESS_ORDER_ALREADY_FILLED = 'BUSINESS.ORDER_ALREADY_FILLED',
  BUSINESS_TRADING_SUSPENDED = 'BUSINESS.TRADING_SUSPENDED',
  BUSINESS_INVALID_SYMBOL = 'BUSINESS.INVALID_SYMBOL',
  BUSINESS_SLIPPAGE_EXCEEDED = 'BUSINESS.SLIPPAGE_EXCEEDED',
  BUSINESS_MIN_ORDER_SIZE = 'BUSINESS.MIN_ORDER_SIZE',
  BUSINESS_MAX_ORDER_SIZE = 'BUSINESS.MAX_ORDER_SIZE',
  BUSINESS_STRATEGY_NOT_ELIGIBLE = 'BUSINESS.STRATEGY_NOT_ELIGIBLE',
  BUSINESS_ALGORITHM_NOT_REGISTERED = 'BUSINESS.ALGORITHM_NOT_REGISTERED',
  BUSINESS_INSTRUMENT_UNIVERSE_UNRESOLVED = 'BUSINESS.INSTRUMENT_UNIVERSE_UNRESOLVED',
  BUSINESS_BACKTEST_IN_PROGRESS = 'BUSINESS.BACKTEST_IN_PROGRESS',

  // ============================================
  // External Service Errors (EXTERNAL.*)
  // ============================================
  EXTERNAL_EXCHANGE_ERROR = 'EXTERNAL.EXCHANGE_ERROR',
  EXTERNAL_EXCHANGE_UNAVAILABLE = 'EXTERNAL.EXCHANGE_UNAVAILABLE',
  EXTERNAL_EXCHANGE_RATE_LIMITED = 'EXTERNAL.EXCHANGE_RATE_LIMITED',
  EXTERNAL_EXCHANGE_AUTH_FAILED = 'EXTERNAL.EXCHANGE_AUTH_FAILED',
  EXTERNAL_COINGECKO_ERROR = 'EXTERNAL.COINGECKO_ERROR',
  EXTERNAL_SERVICE_TIMEOUT = 'EXTERNAL.SERVICE_TIMEOUT',

  // ============================================
  // Internal Server Errors (INTERNAL.*)
  // ============================================
  INTERNAL_SERVER_ERROR = 'INTERNAL.SERVER_ERROR',
  INTERNAL_DATABASE_ERROR = 'INTERNAL.DATABASE_ERROR',
  INTERNAL_UNEXPECTED_ERROR = 'INTERNAL.UNEXPECTED_ERROR'
}
