import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';

/**
 * Individual algorithm activation item in the list
 */
export class AlgorithmActivationListItemDto {
  @ApiProperty({ description: 'Algorithm activation ID' })
  id: string;

  @ApiProperty({ description: 'Algorithm ID' })
  algorithmId: string;

  @ApiProperty({ description: 'Algorithm name' })
  algorithmName: string;

  @ApiProperty({ description: 'User ID' })
  userId: string;

  @ApiProperty({ description: 'User email' })
  userEmail: string;

  @ApiProperty({ description: 'Whether the algorithm is currently active' })
  isActive: boolean;

  @ApiProperty({ description: 'Allocation percentage', example: 5.0 })
  allocationPercentage: number;

  @ApiPropertyOptional({ description: 'When the algorithm was activated' })
  activatedAt?: string;

  @ApiPropertyOptional({ description: 'When the algorithm was deactivated' })
  deactivatedAt?: string;

  @ApiProperty({ description: 'Total orders generated by this activation' })
  totalOrders: number;

  @ApiProperty({ description: 'Orders in the last 24 hours' })
  orders24h: number;

  @ApiProperty({ description: 'Total trading volume', example: 50000.5 })
  totalVolume: number;

  @ApiPropertyOptional({ description: 'Current ROI percentage', example: 2.5 })
  roi?: number;

  @ApiPropertyOptional({ description: 'Win rate', example: 0.65 })
  winRate?: number;

  @ApiPropertyOptional({ description: 'Sharpe ratio', example: 1.2 })
  sharpeRatio?: number;

  @ApiPropertyOptional({ description: 'Maximum drawdown percentage', example: 15.3 })
  maxDrawdown?: number;

  @ApiPropertyOptional({ description: 'Average slippage in basis points', example: 12.5 })
  avgSlippageBps?: number;

  @ApiProperty({ description: 'Exchange name used for this activation' })
  exchangeName: string;

  @ApiProperty({ description: 'When the activation record was created' })
  createdAt: string;
}

/**
 * Paginated response for algorithm activations
 */
export class PaginatedAlgorithmListDto {
  @ApiProperty({ description: 'List of algorithm activations', type: [AlgorithmActivationListItemDto] })
  data: AlgorithmActivationListItemDto[];

  @ApiProperty({ description: 'Total number of items matching the filter' })
  total: number;

  @ApiProperty({ description: 'Current page number' })
  page: number;

  @ApiProperty({ description: 'Number of items per page' })
  limit: number;

  @ApiProperty({ description: 'Total number of pages' })
  totalPages: number;

  @ApiProperty({ description: 'Whether there is a next page' })
  hasNextPage: boolean;

  @ApiProperty({ description: 'Whether there is a previous page' })
  hasPreviousPage: boolean;
}
