name: Claude Code

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@claude') || contains(github.event.issue.title, '@claude')))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}

          # Optional: Specify model (defaults to Claude Sonnet 4, uncomment for Claude Opus 4)
          model: 'claude-3-5-haiku-20241022'

          # Optional: Customize the trigger phrase (default: @claude)
          # trigger_phrase: "/claude"

          # Optional: Trigger when specific user is assigned to an issue
          # assignee_trigger: "claude-bot"

          # Optional: Allow Claude to run specific commands
          allowed_tools:
            'Bash(npm run lint),Bash(npm run test),Bash(npm run build),Bash(nx affected:test),Bash(nx affected:lint)'

          # Optional: Add custom instructions for Claude to customize its behavior for your project
          custom_instructions: |
            This is an Nx monorepo with Angular frontend (apps/chansey) and NestJS API (apps/api).
            Follow the project's ESLint and Prettier configurations.
            Use npm run commands as defined in CLAUDE.md.
            Prioritize understanding exchange integration patterns and background job processing.

          # Optional: Custom environment variables for Claude
          # claude_env: |
          #   NODE_ENV: test
